#pragma once

namespace GA_G {
	enum GA_G {
		PROFILE_ID_ASSAULT = 0x2A8, // 680
		PROFILE_ID_MEDIC = 0x237, // 567
		PROFILE_ID_RECON = 0x2A9, // 681
		PROFILE_ID_ROBOTIC = 0x2A7, // 679

		SKILL_GROUP_SET_ID_ASSAULT = 19,
		SKILL_GROUP_SET_ID_MEDIC = 11,
		SKILL_GROUP_SET_ID_RECON = 17,
		SKILL_GROUP_SET_ID_ROBOTIC = 18,
		SKILL_GROUP_SET_ID_DEVCLASS = 5,
		SKILL_GROUP_SET_ID_NEW_CHARACTER = 23,
		
		HEAD_ASM_ID_TROLL = 2842,

		DYE_ID_NONE_MORE_BLACK = 7552,

		GENDER_TYPE_ID_FEMALE = 852,
		GENDER_TYPE_ID_MALE = 853,

		QUEUE_TYPE_VALUE_ID_1 = 0x58C,
		QUEUE_TYPE_VALUE_ID_2 = 0x58D,
		QUEUE_TYPE_VALUE_ID_3 = 0x5AE,
		QUEUE_TYPE_VALUE_ID_4 = 0x3FD,
		QUEUE_TYPE_VALUE_ID_5 = 0x3FE,

		// TgDevice::m_nDeviceType
		TGDT_RANGED = 388,
		TGDT_SPECIALTY = 981,
		TGDT_MELEE = 389,
		TGDT_OFF_HAND = 390,
		TGDT_BASE_HUMAN_ATTRIB = 392, // REST device
		TGDT_PLAYER_SENSOR = 393, // beacon slot perhaps?
		TGDT_MORALE = 476,
		TGDT_TRAVEL = 806, // jetpack

		EQUIP_POINT_JETPACK_ID = 5,

		BOT_TYPE_VALUE_ID_AGENT = 373,
		BOT_TYPE_VALUE_ID_ELITE = 1101,
		BOT_TYPE_VALUE_ID_BOSS = 1100,
		BOT_TYPE_VALUE_ID_GUARDIAN = 1099,

		BODY_ASM_ID_AGENT = 2685,
		BODY_ASM_ID_SUPPORT_GUARDIAN = 757,
		BODY_ASM_ID_ELITE_TECHRO = 2179,
		BODY_ASM_ID_ELITE_ASSASSIN = 2176,
		BODY_ASM_ID_ELITE_HELOT = 2177,
		BODY_ASM_ID_THINKTANK_BOSS = 2105,

		BOT_ID_SUPPORT_GUARDIAN = 1384,
		BOT_ID_ELITE_TECHRO = 1432,
		BOT_ID_ELITE_ASSASSIN = 1320,
		BOT_ID_ELITE_HELOT = 1321,
		BOT_ID_THINKTANK_BOSS = 1417,

		PHYSICAL_TYPE_VALUE_ID_AGENT = 860,
		PHYSICAL_TYPE_VALUE_ID_THINKTANK = 973,
		PHYSICAL_TYPE_VALUE_ID_GUARDIAN = 861,
	};
};

