#pragma once

namespace GA_G {
	enum GA_G {
		PROFILE_ID_ASSAULT = 0x2A8, // 680
		PROFILE_ID_MEDIC = 0x237, // 567
		PROFILE_ID_RECON = 0x2A9, // 681
		PROFILE_ID_ROBOTIC = 0x2A7, // 679

		SKILL_GROUP_SET_ID_ASSAULT = 19,
		SKILL_GROUP_SET_ID_MEDIC = 11,
		SKILL_GROUP_SET_ID_RECON = 17,
		SKILL_GROUP_SET_ID_ROBOTIC = 18,
		SKILL_GROUP_SET_ID_DEVCLASS = 5,
		SKILL_GROUP_SET_ID_NEW_CHARACTER = 23,
		
		HEAD_ASM_ID_TROLL = 2842,

		DYE_ID_NONE_MORE_BLACK = 7552,

		GENDER_TYPE_ID_FEMALE = 852,
		GENDER_TYPE_ID_MALE = 853,

		QUEUE_TYPE_VALUE_ID_1 = 0x58C,
		QUEUE_TYPE_VALUE_ID_2 = 0x58D,
		QUEUE_TYPE_VALUE_ID_3 = 0x5AE,
		QUEUE_TYPE_VALUE_ID_4 = 0x3FD,
		QUEUE_TYPE_VALUE_ID_5 = 0x3FE,
	};
};

