#pragma once

#include <string>
#include <cstdint>

// IpcProtocol.hpp -- Shared IPC message type constants and wire format documentation.
// ARCH: This file must compile on both i686 (DLL, Windows/Wine) and x86_64 (control server, Linux).
//       Include ONLY standard C++ headers. Never include pch.hpp, windows.h, or SDK headers.

namespace IpcProtocol {

// ---------------------------------------------------------------------------
// Message type strings (used in JSON "type" field)
// ---------------------------------------------------------------------------

constexpr const char* MSG_PING = "PING";
constexpr const char* MSG_PONG = "PONG";

constexpr const char* MSG_PLAYER_REGISTER     = "PLAYER_REGISTER";
constexpr const char* MSG_PLAYER_REGISTER_ACK = "PLAYER_REGISTER_ACK";

constexpr const char* MSG_INSTANCE_HELLO     = "INSTANCE_HELLO";
constexpr const char* MSG_INSTANCE_HELLO_ACK = "INSTANCE_HELLO_ACK";
constexpr const char* MSG_INSTANCE_READY     = "INSTANCE_READY";

constexpr const char* MSG_GAME_EVENT      = "GAME_EVENT";
constexpr const char* MSG_GET_RANDOMSM    = "GET_RANDOMSM";
constexpr const char* MSG_RANDOMSM_RESULT = "RANDOMSM_RESULT";

// ---------------------------------------------------------------------------
// IPC transport
// ---------------------------------------------------------------------------

// Default port for the IPC TCP socket (DLL connects, control server listens).
// Configurable via CLI arg --ipc-port on the control server side.
constexpr uint16_t DEFAULT_IPC_PORT = 9010;

// ---------------------------------------------------------------------------
// GUID format documentation
// ---------------------------------------------------------------------------
//
// Session GUIDs are 32-character lowercase hex strings with NO dashes.
// Example: "a3f2c1d8e4b06912345678abcdef1234"
//
// Generated by TcpSession::GenerateSessionGuid() which XORs timestamp + counter
// bytes through a random seed and formats as %02x.
//
// Never convert to/from UUID dash format -- use the 32-hex-char form everywhere
// (PlayerRegistry lookups, IPC messages, log output).

} // namespace IpcProtocol
