#pragma once

#include <string>
#include <cstdint>

// IpcProtocol.hpp -- Shared IPC message type constants and wire format documentation.
// ARCH: This file must compile on both i686 (DLL, Windows/Wine) and x86_64 (control server, Linux).
//       Include ONLY standard C++ headers. Never include pch.hpp, windows.h, or SDK headers.

namespace IpcProtocol {

// ---------------------------------------------------------------------------
// Message type strings (used in JSON "type" field)
// ---------------------------------------------------------------------------

constexpr const char* MSG_PING = "PING";
constexpr const char* MSG_PONG = "PONG";

constexpr const char* MSG_PLAYER_REGISTER     = "PLAYER_REGISTER";
constexpr const char* MSG_PLAYER_REGISTER_ACK = "PLAYER_REGISTER_ACK";

// Sent by the control server when the client emits PLAYER_LEAVE_GAME (0x0200)
// over TCP. The game DLL looks up the UDP UNetConnection by session_guid and
// invokes NetConnection__Cleanup so the stale Pawn/PlayerController and the
// ClientConnections entry are torn down immediately rather than waiting for
// the engine's 30s ConnectionTimeout — without this, picking a character
// again after Disconnect routes the new HELLO packets through a stale
// USOCK_Open connection and the client times out back to login.
constexpr const char* MSG_PLAYER_LEAVE = "PLAYER_LEAVE";

constexpr const char* MSG_INSTANCE_HELLO     = "INSTANCE_HELLO";
constexpr const char* MSG_INSTANCE_HELLO_ACK = "INSTANCE_HELLO_ACK";
constexpr const char* MSG_INSTANCE_READY     = "INSTANCE_READY";

constexpr const char* MSG_GAME_EVENT      = "GAME_EVENT";
constexpr const char* MSG_ADMIN_ACTION    = "ADMIN_ACTION";
constexpr const char* MSG_ADMIN_ACTION_ACK = "ADMIN_ACTION_ACK";

constexpr const char* MSG_PLAYER_JOINED  = "PLAYER_JOINED";
constexpr const char* MSG_PLAYER_LEFT    = "PLAYER_LEFT";
constexpr const char* MSG_INSTANCE_EMPTY = "INSTANCE_EMPTY";

// Sent by a mission instance at end-of-mission to ask the control server to
// pre-warm a home map instance. The control server reuses the same on-demand
// spawn callback the login flow uses; this just front-runs it so the home
// map is READY by the time the player clicks "End Mission" (which fires
// GSC_CHANGE_INSTANCE{0,0} → control server routes them home).
constexpr const char* MSG_NEED_HOME_MAP = "NEED_HOME_MAP";

// Sent by a mission instance from inside BeginEndMission. Tells the control
// server (a) stamp end_mission_at on the ga_instances row, and (b) flip any
// DRAFTING successor instance for this parent to READY. After this fires,
// GSC_CHANGE_INSTANCE{0,0} from any player in this mission consults the
// stamped end_mission_at + the queue's continue_in_queue config to decide
// whether to route them home or to the successor.
//   { "type": "MISSION_ENDED", "instance_id": <int64> }
constexpr const char* MSG_MISSION_ENDED = "MISSION_ENDED";

// Sent by a mission instance at the game-mode-specific pre-warm trigger
// (e.g. when one team passes the 50% threshold, or a 60s-remaining alert
// fires — exact trigger TBD per game mode). Asks the control server to
// spawn a successor instance for the same queue and bind it to this
// mission via predecessor_instance_id. Idempotent — control server dedupes
// against existing DRAFTING/READY successors of the same parent.
//   { "type": "REQUEST_SUCCESSOR", "instance_id": <int64> }
constexpr const char* MSG_REQUEST_SUCCESSOR = "REQUEST_SUCCESSOR";

constexpr const char* MSG_PLAYER_ACTION = "PLAYER_ACTION";

// ---------------------------------------------------------------------------
// IPC transport
// ---------------------------------------------------------------------------

// Default port for the IPC TCP socket (DLL connects, control server listens).
// Configurable via CLI arg --ipc-port on the control server side.
constexpr uint16_t DEFAULT_IPC_PORT = 9010;

// ---------------------------------------------------------------------------
// GUID format documentation
// ---------------------------------------------------------------------------
//
// Session GUIDs are 32-character lowercase hex strings with NO dashes.
// Example: "a3f2c1d8e4b06912345678abcdef1234"
//
// Generated by TcpSession::GenerateSessionGuid() which XORs timestamp + counter
// bytes through a random seed and formats as %02x.
//
// Never convert to/from UUID dash format -- use the 32-hex-char form everywhere
// (PlayerRegistry lookups, IPC messages, log output).

} // namespace IpcProtocol
