name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts from latest successful build
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          branch: ${{ github.event.release.target_commitish }}
          name: version.dll
          path: out/

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Upload DLL to Release
        run: gh release upload "${{ github.event.release.tag_name }}" out/version.dll --clobber

